# ---
# jupyter:
#   jupytext:
#     cell_metadata_filter: -all
#     notebook_metadata_filter: kernelspec,jupytext
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.1
# ---

# %% [markdown]
# # Generative Models and LLMs
#
# ## The connection between Lindholm-style generative models and LLMs
#
# The shared idea is that a generative model tries to describe how data could have been produced.
#
# For Lindholm's models:
#
# - a GMM says data is generated by first choosing a class or component, then sampling from a Gaussian.
#
# For an LLM:
#
# - text is generated by repeatedly choosing the next token given the tokens that came before it.
#
# So both are generative because both learn a probability distribution over data and can sample from it.
#
# ## Intuitive picture
#
# A generative model answers:
#
# How could data like this have been produced?
#
# Simple comparison:
#
# - GMM: pick cluster, then sample point.
# - LLM: read previous tokens, then sample next token.
#
# The difference is mostly in the structure of the model:
#
# - GMMs are small, explicit, and make strong assumptions such as Gaussian components.
# - LLMs are large neural models that learn sequence structure from data.
#
# ## Math bridge
#
# In a Lindholm-style generative classifier,
#
# $$
# p(x,y) = p(x \mid y)p(y).
# $$
#
# If the label is hidden, we model the observed data by marginalising over the label:
#
# $$
# p(x) = \sum_y p(x \mid y)p(y).
# $$
#
# For text, let a sequence be
#
# $$
# x = (x_1, x_2, \dots, x_T).
# $$
#
# An LLM models the joint probability of the whole sequence using the chain rule. This decomposition is exact, not an approximation. The modelling choice is in how each conditional $p(x_t \mid x_{<t})$ is parameterised, for example with a transformer:
#
# $$
# p(x_1, x_2, \dots, x_T)
# =
# p(x_1)\,p(x_2 \mid x_1)\,p(x_3 \mid x_1, x_2)\cdots p(x_T \mid x_1, \dots, x_{T-1}).
# $$
#
# This is why next-token prediction is still generative: if you know all of these conditional probabilities, you have the joint distribution over sequences.
#
# ## Useful side-by-side view
#
# GMM:
#
# $$
# p(x)=\sum_{m=1}^{M}\pi_m \mathcal{N}(x \mid \mu_m,\Sigma_m)
# $$
#
# LLM:
#
# $$
# p(x)=\prod_{t=1}^{T} p(x_t \mid x_{<t})
# $$
#
# Both are valid generative models.
# They just choose different ways to represent the data distribution.
#
# Final intuition:
#
# - GMM says "data comes from one of these Gaussian components".
# - LLM says "text unfolds step by step, conditioned on what came before".
#
# ## What "probability distribution over text" means
#
# It means the model assigns probabilities to possible text continuations or full text sequences.
#
# Example:
#
# Given the context
#
# `The capital of France is`
#
# the model might assign:
#
# - `Paris`: high probability,
# - `London`: lower probability,
# - `banana`: extremely low probability.
#
# So for any context, the model gives a probability distribution over possible next tokens. Those probabilities sum to 1 across all possible next-token choices.
#
# For a whole sentence, the model builds the probability one step at a time.
#
# For example, the probability of
#
# `The capital of France is Paris`
#
# is built from multiplying conditional probabilities across the sequence.
#
# Toy intuition:
#
# Given
#
# `I drink my coffee with`
#
# the model might assign:
#
# - `milk` = 0.45
# - `sugar` = 0.30
# - `salt` = 0.01
#
# Likely continuations get higher probability; unlikely or nonsensical continuations get lower probability.
#
# To actually generate text, the model samples from this distribution at each step. Controls like temperature (scaling the logits to sharpen or flatten the distribution) and top-k/top-p (restricting which tokens are eligible) shape how deterministic or creative the output is.
#
# ## Practical takeaway
#
# The conceptual bridge is:
#
# - Lindholm generative models learn a distribution for how data points arise,
# - LLMs learn a distribution for how token sequences arise.
#
# Same core idea: model the data-generating process probabilistically.
# Different parameterisation: mixture components for GMMs, autoregressive next-token conditionals for LLMs.
#
# ## Acknowlegments & References:
# Back and forth discussion with GPT-5.4 & Opus-4.6 about chapter 10 of Lindholm and how it relates to LLMs.
